// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhijzkimxefvkoylryhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoaWp6a2lteGVmdmtveWxyeWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTc1ODgsImV4cCI6MjA2NzY3MzU4OH0.x0msVAI1Ytw9NFFx3n9SLpQ-PkfcBBZh3FQYQpN2F4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    debug: false
  },
  realtime: {
    timeout: 90000, // Increased timeout for stability
    heartbeatIntervalMs: 30000, // Less frequent heartbeats
    params: {
      eventsPerSecond: 5 // Reduced event rate
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web'
    }
  }
});